### PR TITLE
Microblaze ESIL 

### PR DESCRIPTION
**Pull request by sylvainpelissier**
- Carry flag
- Load and store with immediate
- Logical instructions with immediate

### CODE REVIEW

**Comment by radare** [comment]
Just un tiem for the rls!

**Comment by sylvainpelissier** [comment]
Is there something preventing to accept this request ?

**Comment by Maijin** [comment]
Yes conflicts in  `microblaze/anal/anal_microblaze_gnu.c `

**Comment by sylvainpelissier** [comment]
Sorry I miss that, it should be fine now.

**Comment by radare** [comment]
Can you please fix the rebase? I cant. MErge from the github web :/

**Comment by sylvainpelissier** [comment]
Should be ok now.

**Pull request merged**
