### PR TITLE
GitHub CI: Point to correct repo, use new flag && fix badge

### LINKED ISSUE #258: Switch to gitlab-ci and make it green
**Describe the issue**

r2 master is now using gitlab-ci, will be good that all the plugins in here do the same and we may probably find a better approach

**How to reproduce?**

**Expected behavior**

**Possible fix**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by zamaudio**
**Detailed description**

r2 repo was pointing to my personal fork for testing previously.  Now that r2pm has R2PM_GITSKIP in master, use it.
Also, fix badge not displaying on readme.

**Test plan**

See PR github ci, it should pass.

**Closing issues**

Closes #258

### CODE REVIEW

**Comment by zamaudio** [comment]
It failed on vc4 with
`#error You can't have CGEN_MAX_EXTRA_OPCODE_OPERANDS with CGEN_INT_INSN_P.`

**Comment by zamaudio** [comment]
Huh?
```
rlang-duktape
Cloning into 'radare2-rlang'...
Install Done For rlang-duktape
Makefile:1: config.mk: No such file or directory
make: *** No rule to make target 'config.mk'.  Stop.
Error: Process completed with exit code 1.
```

**Comment by trufae** [comment]
Looks red. but probably unrelated to this pr. can u fix the others or do you prefer to do so in a separate PR?

**Comment by zamaudio** [comment]
Let's fix all the others and I can keep bumping this one until it's green

**Comment by zamaudio** [comment]
Ugh, I have no idea why this failed in the CI:
```
rlang-duktape
Cloning into 'radare2-rlang'...
fatal: unable to access 'https://github.com/radareorg/radare2-rlang/': Failed to connect to github.com port 443: Connection refused
ERROR: Oops
```

**Comment by zamaudio** [comment]
:tada:

**Comment by trufae** [comment]
Great!

**Pull request merged**
