### PR TITLE
Fix #228 - Pyc disassembler

### LINKED ISSUE #228: Could not disassemble python opcode
**Describe the issue**
Python plugin could not perform simple disassembly. On further inspection, it seems that the current code is trying to perform analysis on bytecode rather than disassembling opcode
```
$> rasm2 -L | grep pyc
_d__  32         pyc         LGPL3   PYC disassemble plugin
```

**How to reproduce?**
```
$> rasm2 -a pyc -d 090909
invalid
invalid
invalid
```

**Expected behavior**
```
$> rasm2 -a pyc -d 090909
NOP
NOP
NOP
```

**Possible fix**
Implement disassembly of opcodes

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by x0urc3**
**Detailed description**
Implementation of pyc disassembler

...

**Test plan**

```
cat fhello.py
def hello():
    print("hello world!\n")

if __name__ == "__main__":
    import sys
    import dis
    import binascii

    code=hello.__code__.co_code
    print("code: {}".format(binascii.b2a_hex(code)))
    dis.dis(hello.__code__.co_code)
$> python2.7 fhello.py
code: 640100474864000053
          0 LOAD_CONST          1 (1)
          3 PRINT_ITEM     
          4 PRINT_NEWLINE  
          5 LOAD_CONST          0 (0)
          8 RETURN_VALUE   
$> rasm2 -a pyc -d 640100474864000053
LOAD_CONST 1
PRINT_ITEM
PRINT_NEWLINE
LOAD_CONST 0
RETURN_VALUE
$> python3.7 fhello.py
code: b'740064018301010064005300'
          0 LOAD_GLOBAL              0 (0)
          2 LOAD_CONST               1 (1)
          4 CALL_FUNCTION            1
          6 POP_TOP
          8 LOAD_CONST               0 (0)
         10 RETURN_VALUE
$> rasm2 -a pyc -d 740064018301010064005300
LOAD_GLOBAL 0
LOAD_CONST 1
CALL_FUNCTION 1
POP_TOP
LOAD_CONST 0
RETURN_VALUE
```
...

**Closing issues**

Closes #228 
Related radareorg/radare2#4228
...

### CODE REVIEW

**Comment by x0urc3** [comment]
- Works well for Python <3.6. 
- New Python version changes the size of the operand, so I need to use the identified version information from RBinPlugin
- Is there any 'clean' way I could get the populated RBinInfo struct into RAsmPlugin ?

**Comment by radare** [comment]
> On 6 Feb 2020, at 08:56, Khairulmizam Samsudin <notifications@github.com> wrote:
> 
> ﻿
> Works well for Python <3.6.
> New Python version changes the size of the operand, so I need to use the identified version information from RBinPlugin
> Is there any 'clean' way I could get the populated RBinInfo struct into RAsmPlugin ?

Theres a shared pointer way that is used for java and dex but i wouldnt consider this as clean

**Comment by x0urc3** [comment]
> Theres a shared pointer way that is used for java and dex but i wouldnt consider this as clean

```
RBin *bin = a->binb.bin;
RBinPlugin *plugin = bin && bin->cur && bin->cur->o ?
                bin->cur->o->plugin : NULL;
```

Hmm doesn't seem to work anymore. Inspected with GDB and  a->binb is null

**Comment by x0urc3** [comment]
Decided to use architecture bits to differentiate between operand size. What do you think @radare ?

**Comment by radare** [comment]
you can also use asm.cpu, but i guess bits is fine if it works for now

**Pull request merged**
