### PR TITLE
atombios: Make plugins compile again && GitHub CI

### PR DESCRIPTION
**Pull request by zamaudio**
This makes atombios asm/anal/bin plugins all work again.  Previously they would not compile.

image

### CODE REVIEW

**Comment by zamaudio** [comment]
Needed to introduce GitHub CI so I could add a compile test for atombios.

**Comment by trufae** [comment]
Lgtm. Its ready to merge?

**Comment by zamaudio** [comment]
This change is ready, but it depends on a new change that I will submit to r2 for R2PM_GITMASTER env var, once it passes the test locally I will send in the PR.

**Comment by zamaudio** [comment]
Closes #258

**Pull request merged**
