### PR TITLE
Improve BA2 analyser

### PR DESCRIPTION
**Pull request by Jerome-PS**
**Detailed description**

Small improvements on the BA2 analyser.

...

**Test plan**

Opened a few elf files.

### CODE REVIEW

**Comment by Jerome-PS** [comment]
Hi,

Is this the proper way to add information in the analyser (this allowed me to see cross-references for data symbols I could not see before, even though I had ESIL - but I fixed a but in the ESIL address computation as well, so I'm not sure which made it work)?
Is filling in the ptr and/or val structure member not redundant with ESIL?
What about the reg and dest members of the structure? Are they needed? Do they replace val/ptr? Should r0 (not a real register, always value 0) be treated specially as I did, or should it be done differently? How to fill in the ptr value, when it is offset by the contents of a register?

**Comment by trufae** [comment]
ping

**Comment by Jerome-PS** [comment]
> ping

Hi is there a tool that formats the code automatically?

**Comment by trufae** [comment]
Sys/indent.sh

**Comment by trufae** [comment]
cant merge because of conflicts

**Pull request merged**
