### PR TITLE
Translate arm64 analysis to v35 disassembler

### PR DESCRIPTION
**Pull request by aemmitt-ns**
**Detailed description**

Add code for capstone arm64 plugin to vector35 plugin by converting fields where necessary and other minor changes. Mostly things map well from one to the other. 

**Test plan**

I will eventually try to get the whole arm64 test suite working, and also add tests for new instructions that weren't covered previously.

### CODE REVIEW

**Comment by aemmitt-ns** [comment]
I still need to add support for my recent additions of floating point instructions and a small subset of vector instructions and single lane vector register operands.

**Comment by trufae** [comment]
i think is better to drop the DRAFT bit, otherwise the CI wont run and test this code. current master is not building for me because of changes in the v35 api. so imho its good to merge whenever you say :) Awesome work!

**Comment by aemmitt-ns** [comment]
Should be nearly ready to merge but it still produces a ton of "WARNING: r_strbuf_append: assertion 'sb && s' failed (line 215)". Trying to figure out where they are comin from. Some of the vector code is still not correct because there isn't a good mapping from CS to v35 fields.

**Comment by aemmitt-ns** [comment]
oh also i added the "git checkout master" to fix the issues from v35 in the default staging branch

**Comment by aemmitt-ns** [comment]
Converted the old anop64 function to v35 and the analysis is now basically the same as with the capstone plugin, the same function counts and sizes in my test binaries. one issue was instead of op->cond for things like b.ne v35 has separate instructions ARM64_B_NE. Need to make sure they have ESIL expressions now

**Comment by aemmitt-ns** [comment]
Alright csel/cset/cinc are fixed now, the calling convention warnings are gone, its ready to merge. The analysis is now the same as the capstone plugin in almost every way (I think). It definitely needs to be tested a ton more before going into core though.

**Comment by aemmitt-ns** [comment]
Currently there is a fatal error generated for any large binary when searching for ldr instrs `undefined symbol: get_system_register_name`. There must be some sort of linking issue, can't figure it out though.

**Comment by trufae** [comment]
That's what i get on macOS:

```
Undefined symbols for architecture x86_64:
  "_get_system_register_name", referenced from:
      _get_register in format.o
      _aarch64_disassemble in format.o
      _decode_scratchpad in decode_scratchpad.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by trufae** [comment]
merged, i fixed the issue in master.

awesome work!! time to test!

**Pull request merged**
